vim.cmd "set title"

require "nemo.globals"
require "nemo.options"
require "nemo.mappings"
require "nemo.autocmds"
require "nemo.plugins.packer"
require "nemo.plugins.treesitter"
require "nemo.plugins.cmp"
require "nemo.plugins.lspconfig"
require "nemo.plugins.null-ls"
require "nemo.plugins.telescope"
require "nemo.plugins.luasnip"
require "nemo.plugins.illuminate"
require "nemo.plugins.tree"
require "nemo.plugins.autopairs"
-- require "nemo.colorschemes.gruvbox"
require "nemo.colorschemes.nightfox"
require "nemo.abbreviations"
require "nemo.plugins.comment"
require "nemo.plugins.indent-blankline"
-- require "nemo.plugins.lspsaga"
